# Generated by Django 4.2.27 on 2026-03-31 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(default='Backend Intern', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.CharField(default='HTML, CSS, Django', max_length=200),
            preserve_default=False,
        ),
    ]
