# Generated by Django 4.2.27 on 2026-04-02 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
